name: Deploy Hello K8S

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      ENV:
        description: environment to deploy
        default: dev
        required: false
jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: deploy
      run: |
        bash ./devops/scripts/runpipeline.sh
      env:
        ENV: ${{ github.event.inputs.ENV }} 
