---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conntest-v1
  namespace: default
  labels:
    app: conntest
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conntest
      version: v1
  template:
    metadata:
      labels:
        app: conntest
        version: v1
    spec:
      containers:
      - name: conntest
        image: docker-registry.umusic.com/devops/conntest:v0.0.1
        args:
        - server
        - -p=80
        ports:
        - containerPort: 80
          name: http
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          requests:
            cpu: 500m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 500Mi
      imagePullSecrets:
      - name: regcred
